name: Publish to npm

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: false

      - name: Run example (basic test)
        run: npm run example
        env:
          PUPPETEER_SKIP_DOWNLOAD: false

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUPPETEER_SKIP_DOWNLOAD: true
